<?php
// +----------------------------------------------------------------------
// | Copyright (c) 2016 http://www.noble-spirits.com All rights reserved.
// +----------------------------------------------------------------------
// 模块信息配置
return array (
	// @formatter:off
	'info' => array (
		'name' => 'Admin',
		'title' => '系统',
		'icon' => 'fa fa-cog',
		'icon_color' => '#3CA6F1',
		'description' => '核心系统',
		'developer' => '诺伯丝聚酿国际贸易（上海）有限公司',
		'website' => 'http://www.noble-spirits.com',
		'version' => '1.0.0' ),
	// @formatter:on
	'admin_menu' => array (1 => array ('id' => 1,'pid' => '0','title' => '系统','url' => '','icon' => 'fa fa-cog' ),
		2 => array ('pid' => '1','title' => '系统功能','icon' => 'fa fa-folder-open-o','id' => 2 ),
		201 => array ('pid' => '2','title' => '生成二维码','icon' => 'fa fa-folder-open-o','url' => 'Admin/Qrcode/gen_qrcode','id' => 201 ),
		3 => array ('pid' => '2','title' => '系统设置','icon' => 'fa fa-wrench','url' => 'Admin/Config/group','id' => 3 ),
		4 => array ('pid' => '3','title' => '修改设置','url' => 'Admin/Config/groupSave','id' => 4 ),
// 		5 => array ('pid' => '2','title' => '导航管理','icon' => 'fa fa-map-signs','url' => 'Admin/Nav/index','id' => 5 ),
// 		6 => array ('pid' => '5','title' => '新增','url' => 'Admin/Nav/add','id' => 6 ),
// 		7 => array ('pid' => '5','title' => '编辑','url' => 'Admin/Nav/edit','id' => 7 ),
// 		8 => array ('pid' => '5','title' => '设置状态','url' => 'Admin/Nav/setStatus','id' => 8 ),
		13 => array ('pid' => '2','title' => '配置管理','icon' => 'fa fa-cogs','url' => 'Admin/Config/index','id' => 13 ),
		14 => array ('pid' => '13','title' => '新增','url' => 'Admin/Config/add','id' => 14 ),
		15 => array ('pid' => '13','title' => '编辑','url' => 'Admin/Config/edit','id' => 15 ),
		16 => array ('pid' => '13','title' => '设置状态','url' => 'Admin/Config/setStatus','id' => 16 ),
		17 => array ('pid' => '2','title' => '上传管理','icon' => 'fa fa-upload','url' => 'Admin/Upload/index','id' => 17 ),
		18 => array ('pid' => '17','title' => '上传文件','url' => 'Admin/Upload/upload','id' => 18 ),
		19 => array ('pid' => '17','title' => '删除文件','url' => 'Admin/Upload/delete','id' => 19 ),
		20 => array ('pid' => '17','title' => '设置状态','url' => 'Admin/Upload/setStatus','id' => 20 ),
		21 => array ('pid' => '17','title' => '下载远程图片','url' => 'Admin/Upload/downremoteimg','id' => 21 ),
		22 => array ('pid' => '17','title' => '文件浏览','url' => 'Admin/Upload/fileManager','id' => 22 ),
		23 => array ('pid' => '1','title' => '系统权限','icon' => 'fa fa-folder-open-o','id' => 23 ),
		28 => array ('pid' => '23','title' => '管理员管理','icon' => 'fa fa-lock','url' => 'Admin/Access/index','id' => 28 ),
		29 => array ('pid' => '28','title' => '新增','url' => 'Admin/Access/add','id' => 29 ),
		30 => array ('pid' => '28','title' => '编辑','url' => 'Admin/Access/edit','id' => 30 ),
		31 => array ('pid' => '28','title' => '设置状态','url' => 'Admin/Access/setStatus','id' => 31 ),
		32 => array ('pid' => '23','title' => '用户组管理','icon' => 'fa fa-sitemap','url' => 'Admin/Group/index','id' => 32 ),
		33 => array ('pid' => '32','title' => '新增','url' => 'Admin/Group/add','id' => 33 ),
		34 => array ('pid' => '32','title' => '编辑','url' => 'Admin/Group/edit','id' => 34 ),
		35 => array ('pid' => '32','title' => '设置状态','url' => 'Admin/Group/setStatus','id' => 35 ),
		36 => array ('pid' => '1','title' => '扩展中心','icon' => 'fa fa-folder-open-o','id' => 36 ),
		44 => array ('pid' => '36','title' => '功能模块','icon' => 'fa fa-th-large','url' => 'Admin/Module/index','id' => 44 ),
		45 => array ('pid' => '44','title' => '安装','url' => 'Admin/Module/install','id' => 45 ),
		46 => array ('pid' => '44','title' => '卸载','url' => 'Admin/Module/uninstall','id' => 46 ),
		47 => array ('pid' => '44','title' => '更新信息','url' => 'Admin/Module/updateInfo','id' => 47 ),
		48 => array ('pid' => '44','title' => '设置状态','url' => 'Admin/Module/setStatus','id' => 48 ),
		49 => array ('pid' => '36','title' => '插件管理','icon' => 'fa fa-th','url' => 'Admin/Addon/index','id' => 49 ),
		50 => array ('pid' => '49','title' => '安装','url' => 'Admin/Addon/install','id' => 50 ),
		51 => array ('pid' => '49','title' => '卸载','url' => 'Admin/Addon/uninstall','id' => 51 ),
		52 => array ('pid' => '49','title' => '运行','url' => 'Admin/Addon/execute','id' => 52 ),
		53 => array ('pid' => '49','title' => '设置','url' => 'Admin/Addon/config','id' => 53 ),
		54 => array ('pid' => '49','title' => '后台管理','url' => 'Admin/Addon/adminList','id' => 54 ),
		55 => array ('pid' => '54','title' => '新增数据','url' => 'Admin/Addon/adminAdd','id' => 55 ),
		56 => array ('pid' => '54','title' => '编辑数据','url' => 'Admin/Addon/adminEdit','id' => 56 ),
		57 => array ('pid' => '54','title' => '设置状态','url' => 'Admin/Addon/setStatus','id' => 57 ),
		58 => array ('id' => 58,'pid' => '36','title' => '钩子管理','url' => 'Admin/addon/hooks','icon' => 'fa fa-th' ),
		59 => array ('id' => 59,'pid' => '58','title' => '新增','url' => 'Admin/Addon/addHook','icon' => '' ),
		60 => array ('id' => 60,'pid' => '36','title' => '微信菜单','url' => 'admin/wxmenu/index','icon' => 'fa fa-comment' ),
		61 => array ('pid' => '60','title' => '新增','url' => 'Admin/Wxmenu/add','icon' => 'fa ','id' => 61 ),
		62 => array ('pid' => '60','title' => '编辑','url' => 'Admin/Wxmenu/edit','icon' => 'fa ','id' => 62 ),
		63 => array ('id' => 63,'pid' => '60','title' => '生成菜单','url' => 'Admin/Wxmenu/build','icon' => 'fa ' ),
		64 => array ('pid' => '58','title' => '编辑','url' => 'admin/addon/edithook','icon' => 'fa ','id' => 64 ),
		65 => array ('pid' => '3','title' => '清除缓存','url' => 'admin/index/removeruntime','icon' => 'fa','id' => 65 ),
		67 => array ('pid' => '28','title' => '删除','url' => 'admin/access/setstatus/status/delete','icon' => 'fa ' ) ) );